# The title is the title of your Add-On
title: Export viewer
# The description will be shown above the form when activating the Add-On
description: Export a standalone version of the document viewer that can work without external network access.
# Top level type should always be object
type: object
# How does this add-on accept documents
# If more than one type is specified, the user will be prompted to choose one
documents:
  # By the currently selected documents
  - selected
# Categories are what type of Add-On this is. Used to sort the Add-On in the Add-On menu.
categories:
  - export
# Acceptable categories are premium, ai, export, bulk, file,  monitor, statistical, and extraction.
# You can read more about DocumentCloud Add-On categories here: https://www.documentcloud.org/help/add-ons#types-of-add-ons
