

install:
	@rm -rf documentcloud-frontend
	git clone --depth 1 https://github.com/MuckRock/documentcloud-frontend
	rm -rf documentcloud-frontend/.git
	npm ci

update:
	@rm -rf documentcloud-frontend
	git clone --depth 1 https://github.com/MuckRock/documentcloud-frontend
	rm -rf documentcloud-frontend/.git
	npm up

build:
	npm run build

run:
	npm start
